#!/bin/bash

find . -name "*.class" -exec rm \{\} \;
if [ $# = 0 ]
then
	javac "test/TestMenu.java" && java "test.TestMenu"
else
	javac "test/TestMaps.java" && java "test.TestMaps"
fi
find . -name "*.class" -exec rm \{\} \;
